-- SQL script to insert dummy data into the database
-- Note: Assuming table names are generated by Hibernate (users, products, carts, etc.)

-- 1. Insert Products
INSERT INTO products (name, description, price, stock_quantity, image_url) VALUES 
('Apple iPhone 15 Pro', 'Latest model with A17 Pro chip and titanium design.', 999.00, 50, 'https://example.com/images/iphone15pro.jpg'),
('Sony WH-1000XM5', 'Industry-leading noise canceling wireless headphones.', 348.00, 120, 'https://example.com/images/sonywh1000xm5.jpg'),
('MacBook Pro 16"', 'M3 Max chip, 36GB RAM, 1TB SSD. Built for pros.', 2499.00, 30, 'https://example.com/images/macbookpro.jpg'),
('Samsung Galaxy S24 Ultra', 'AI-powered smartphone with 200MP camera and S-Pen.', 1199.00, 75, 'https://example.com/images/s24ultra.jpg'),
('Nintendo Switch OLED', 'Hybrid console with vibrant 7-inch OLED display.', 349.99, 200, 'https://example.com/images/switcholed.jpg'),
('Logitech MX Master 3S', 'Advanced wireless mouse with ultra-fast scrolling.', 99.99, 150, 'https://example.com/images/mxmaster3s.jpg');

-- 2. Insert Users
-- Passwords are encrypted using BCrypt. The plaintext for both is: password123
INSERT INTO users (username, email, password, role) VALUES 
('admin_user', 'admin@example.com', '$2a$10$wY9qL/L0Y8B5fP.6D3/YTuw..vH91uK10p0/92B9G1U/qFv6Z7D7m', 'ADMIN'),
('john_doe', 'john@example.com', '$2a$10$wY9qL/L0Y8B5fP.6D3/YTuw..vH91uK10p0/92B9G1U/qFv6Z7D7m', 'USER'),
('jane_smith', 'jane@example.com', '$2a$10$wY9qL/L0Y8B5fP.6D3/YTuw..vH91uK10p0/92B9G1U/qFv6Z7D7m', 'USER');

-- 3. Create Carts for the users (Each user must have a 1-to-1 Cart)
-- Assuming the auto-increment user IDs generated above are 1, 2, 3
INSERT INTO carts (user_id) VALUES 
(1), 
(2), 
(3);

-- 4. Insert some initial items into carts (Optional)
-- Adding iPhone(id 1) and Headphones(id 2) to john_doe's (id 2) cart
INSERT INTO cart_items (cart_id, product_id, quantity) VALUES 
(2, 1, 1),
(2, 2, 1);
